module.exports = {
  singleQuote: true,
  bracketSameLine: true,
  bracketSpacing: true,
  printWidth: 120,
  semi: true,
  tabWidth: 2,
  importOrder: [
    '^server-only$',
    '^(react|next)(.*)$',
    '^@shared/(.*)$',
    '^@entities/(.*)$',
    '^@features/(.*)$',
    '^@widgets/(.*)$',
    '^@views/(.*)$',
    '^(.*)$',
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  plugins: ['@trivago/prettier-plugin-sort-imports'],
};
